Fix: Add UUID and ID to field change history
solop-develop/frontend-default-theme pull request #317
Opened 2022-10-03 18:08 UTC by elsiosanchez

https://user-images.githubusercontent.com/45974454/193647954-4a5bc8af-0943-48f9-9ea0-495b04b63b6f.mp4

2022-10-03 18:27 UTC, EdwinBetanc0urt requested changes

2022-10-03 18:27 UTC, EdwinBetanc0urt commented on components/ADempiere/FieldDefinition/FieldOptions/ChangeLogs/index.vue
> +      <p v-if="!isEmptyValue(fieldUuid) && !isEmptyValue(fieldDisplayColumName)">
validate with utils/ADempiere/references SUPPORTED_LOOKUPS and display type.

2022-10-03 18:27 UTC, EdwinBetanc0urt commented on components/ADempiere/FieldDefinition/FieldOptions/ChangeLogs/index.vue
> +    fieldDisplayColumName() {
Remove this computed

2022-10-05 13:20 UTC, elsiosanchez commented on components/ADempiere/FieldDefinition/FieldOptions/ChangeLogs/index.vue
> +      <p v-if="!isEmptyValue(fieldUuid) && !isEmptyValue(fieldDisplayColumName)">
Added support for  SUPPORTED_LOOKUPS

2022-10-05 13:49 UTC, merged